import { SkillNode, SkillEdge } from '@/components/SkillEvolutionGraph';

export const skillNodes: SkillNode[] = [
  {
    id: 'html-css',
    label: 'HTML & CSS',
    category: 'frontend',
    startYear: 2021,
    proficiency: 85,
    learnedContext: 'Started with static websites and landing pages',
  },
  {
    id: 'javascript',
    label: 'JavaScript',
    category: 'frontend',
    startYear: 2021,
    proficiency: 88,
    learnedContext: 'Core language for frontend logic and async flows',
  },
  {
    id: 'react',
    label: 'React',
    category: 'frontend',
    startYear: 2022,
    proficiency: 90,
    learnedContext: 'Built multiple production-ready web apps',
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    category: 'frontend',
    startYear: 2022,
    proficiency: 85,
    learnedContext: 'Adopted for type safety and scalable codebases',
  },
  {
    id: 'node',
    label: 'Node.js',
    category: 'backend',
    startYear: 2022,
    proficiency: 80,
    learnedContext: 'Backend APIs using Express and REST principles',
  },
  {
    id: 'nest',
    label: 'NestJS',
    category: 'backend',
    startYear: 2023,
    proficiency: 78,
    learnedContext: 'Structured backend with modules, guards, and DI',
  },
  {
    id: 'databases',
    label: 'Databases',
    category: 'backend',
    startYear: 2022,
    proficiency: 75,
    learnedContext: 'Worked with MongoDB, PostgreSQL, and schema design',
  },
  {
    id: 'system-design',
    label: 'System Design',
    category: 'system-design',
    startYear: 2023,
    proficiency: 70,
    learnedContext: 'Scalability, trade-offs, and real-world architectures',
  },
  {
    id: 'aws',
    label: 'AWS',
    category: 'cloud',
    startYear: 2024,
    proficiency: 65,
    learnedContext: 'Hands-on EC2, IAM, deployments, and Nginx',
  },
  {
    id: 'docker',
    label: 'Docker',
    category: 'cloud',
    startYear: 2024,
    proficiency: 68,
    learnedContext: 'Containerized backend services for consistency',
  },
];

export const skillEdges: SkillEdge[] = [
  {
    from: 'html-css',
    to: 'javascript',
    yearIntroduced: 2021,
    reason: 'JavaScript enhanced static pages with interactivity',
  },
  {
    from: 'javascript',
    to: 'react',
    yearIntroduced: 2022,
    reason: 'React introduced component-based architecture',
  },
  {
    from: 'react',
    to: 'typescript',
    yearIntroduced: 2022,
    reason: 'TypeScript improved reliability in React apps',
  },
  {
    from: 'javascript',
    to: 'node',
    yearIntroduced: 2022,
    reason: 'Same language used on both frontend and backend',
  },
  {
    from: 'node',
    to: 'databases',
    yearIntroduced: 2022,
    reason: 'Persistent data storage for backend services',
  },
  {
    from: 'node',
    to: 'nest',
    yearIntroduced: 2023,
    reason: 'NestJS brought structure and scalability to Node apps',
  },
  {
    from: 'nest',
    to: 'system-design',
    yearIntroduced: 2023,
    reason: 'Required thinking in modules, boundaries, and scale',
  },
  {
    from: 'system-design',
    to: 'aws',
    yearIntroduced: 2024,
    reason: 'Design decisions influenced cloud architecture choices',
  },
  {
    from: 'aws',
    to: 'docker',
    yearIntroduced: 2024,
    reason: 'Containers simplified deployments and environment parity',
  },
];
